### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by GudeSAT** [danieltroger/telnetd_ramdisk#12]
SRTG: iBoot-2234.0.0.2.22
SRNM: N/A
IMEI: N/A
NONC: 81a6e191420363bd67ab3581d1909a7d83b9f268
SNON: ccfaaa3877a8d63831739fd5f296c5cb14dc1bb3
MODE: DFU
PRODUCT: iPhone8,1
MODEL: n71map
NAME: iPhone 6s

[*] Executing wget https://api.ipsw.me/v2.1/firmwares.json/condensed -O /Users/gude/Desktop/111/telnetd_ramdisk/.cache/firmwares.json

Fatal error: Uncaught TypeError: Return value of get_firmware_data() must be an object, null returned in /Users/gude/Desktop/111/telnetd_ramdisk/functions.php:158
Stack trace:
#0 /Users/gude/Desktop/111/telnetd_ramdisk/functions.php(107): get_firmware_data()
#1 /Users/gude/Desktop/111/telnetd_ramdisk/functions.php(83): find_device(32771, 4)
#2 /Users/gude/Desktop/111/telnetd_ramdisk/functions.php(96): detect_device()
#3 /Users/gude/Desktop/111/telnetd_ramdisk/make_telnet_rd.php(70): read_device()
#4 {main}
  thrown in /Users/gude/Desktop/111/telnetd_ramdisk/functions.php on line 158

**Comment by arx8x** [comment]
is the PC connected to the internet?

If yes, try running
`cd /tmp`
`wget https://api.ipsw.me/v2.1/firmwares.json/condensed -O`
